### PR TITLE
Remove dependency on nightly

### PR DESCRIPTION
**Pull request by ykomatsu**
rls-vscode should work with beta and stable channel.

### CODE REVIEW

**Comment by raggy-rs** [comment]
Yes please!
Without this change the extension is unusable even with nightly if you have nightly-x86_64-pc-windows-msvc installed because nightly defaults to the nightly-i686-pc-windows-gnu.

**Comment by ghisvail** [comment]
You might also want to update the README for completeness:
```
## Requirements
[...]
* A nightly Rust toolchain (the extension will configure this for you, with
  permission)
```
to
```
* A Rust toolchain (the extension will configure this for you, with
  permission)
```

**Comment by Xanewok** [comment]
Yeah, we're using `CONFIGURATION.channel` everywhere else, and since it's available on every channel now, it seems like a good idea to unify this. Thanks!

**Comment by ghisvail** [comment]
Could you release `v0.3.2` with this change in please?

**Pull request merged**
