### PR TITLE
Added check for most recent channel with RLS.

### PR DESCRIPTION
**Pull request by maccoda**
Wanted to have a shot at helping out on this one. I saw what the [Atom Rust IDE](https://github.com/mehcode/atom-ide-rust/tree/master/lib) has done for handling the RLS not being available on every nightly build so tried to take a leaf out of their book. 

This is my first time writing typescript so please let me know if I slipped up anywhere. 👍 

I am hoping this will assist on #237 and give the RLS some breathing room for getting into stable.

One thing that I didn't do but think is probably a useful next step is to make users aware that the configuration item for the channel being used is no longer what it used to start up and install the RLS. Let me know if you want me to have a go at that one, would be happy to help out.

### CODE REVIEW

**Comment by nrc** [comment]
With the latest Rustup, we should never install a toolchain with a missing component without the users forcing the install, so I think we shouldn't need to do this. On the VSCode side, I think we should address the issue by  communicating what is going on to the user - i.e., if we `rustup update`, we only do so if there is an RLS, and if it is missing, we report that to the user (I believe the behaviour is currently correct, but we don't report a specific error to the user), if there is no RLS on the current channel, then we should recommend the user switch and tell them how to do that, but not actually do it, since they are probably in some weird dev scenario in this case (given the rustup change).

**Comment by maccoda** [comment]
@nrc all sounds fair enough. Would a better approach then be to follow on from your last point there and provide a more user friendly notification of RLS not present over the current one which doesn't report it isn't found rather that it failed to install? Further, could perhaps add a section to the documentation to explain how to configure the channel.

Is that more in the direction of what you are looking for?

If so will rework this towards that 👍

**Comment by nrc** [comment]
@maccoda, yes, that all sounds great, thanks!

**Comment by maccoda** [comment]
Going to close this as I haven't had much time unfortunately and honestly really agreed with you that shouldn't touch too much of the user's set up and was realizing most of the things I was thinking of doing would become overly complex/messy. I will probably just post another PR hopefully soon just documenting what I had to do to get the plugin working when the RLS didn't ship as part of the nightly build 👍 Thanks for the help @nrc

**Pull request closed without merging**
