### PR TITLE
Use "Dedicated" instead of "New" panel when building tasks #2

### PR DESCRIPTION
**Pull request by SkyZH**
Last time in #399 , I only fixed `cargo` command. Now all tasks are subject to Dedicated panel. Thanks @jens1o for reminding me.

### CODE REVIEW

**Comment by SkyZH** [comment]
I've tested this PR on my own machine. This time there should be no problem.

image

**Comment by SkyZH** [comment]
image
Each task occupies its own panel.

**Comment by jens1o** [comment]
awesome!

**Comment by Xanewok** [comment]
Weird, the build failure seems unrelated; I'll reopen to trigger CI

**Pull request merged**
